language: java
deploy:
  provider: releases
  api_key:
    secure: dnX/CIskaIMHFl8u8xC/QbpSPDb2Oi4POqP1NWFyFdS994OAHzoQRkAyLXUuyOfoNQZwhxoETli8s8KGaud2XCB6Sgr3drDb5oyRFg7K5c32QrmWNhKROQHdA8qYui302gmJmB/8kcayqMjkF0iOfrSRqHNJeGMAHKO93JFBKio=
  file: build/libs/xld-pause-plugin-4.5.3.jar
  on:
      all_branches: true
      tags: true
notifications:
  hipchat:
    rooms:
      secure: X21FGM3dTp7qdTi1joVMmVgif41rXWYxssm44bcF8YLmzZ4xV3GSTxJgQE1+mELH7B94dcuMcRrQyTiiEQjkHarPG/StC5zN019TWHYvIWE5+o1YZ59VIXlHBBMdj7OlzkYqWwfnaT+ST3gUDDgWKqFtFZ1MVlXdT86EcwZcLME=
